{% set name = "kazoo" %}
{% set version = "2.8.0" %}
{% set sha256 = "588e27868e4a0ed70ae4a7a5b0f3bca4cec5e5c49dbd7e41349c0883182bf2fe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - kazoo

about:
  home: http://github.com/python-zk/kazoo
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Kazoo is a high-level Python library that makes it easier to use Apache Zookeeper
  description: Kazoo is a high-level Python library that makes it easier to use Apache Zookeeper
  doc_url: https://kazoo.readthedocs.io/
  dev_url: https://github.com/python-zk/kazoo
